### ISSUE TITLE
Ora_init_param is being set every puppet run

### ISSUE THREAD

**Issue by cliles** [hajee/oracle#35]
Not sure if related to issue #34 or not, but I seem to have Ora_init_params that are being ensured on every puppet run.

I can dump the spfile from memory after restart and see that my params are set, so this shouldn't be happening. When doing a puppet run in debug I can see trailing whitespace on the parameter.

For example
```
ora_init_param { 'spfile/log_archive_dest_1':
  ensure => present,
  value    => "LOCATION=+ARCLOG/${our_db_name}"
}
```

```
DEBUG: SPFILE,TRUE   ,log_archive_dest_1                                     ,LOCATION=+ARCLOG/dbname
            ,LOCATION=+ARCLOG/dbname
            ,*
```

Please let me know if there is a better way to capture debug output.

**Comment by hajee** [comment]
I can get the same issue only when the variable `$our_db_name` contains a trailing space.

This snippet works ok,

```puppet
$our_db_name = 'aa'
ora_init_param { 'spfile/log_archive_dest_1':
  ensure => present,
  value  => "LOCATION=+ARCLOG/${our_db_name}"
}
```

But when you add a space to the variable `$our_db_name` it runs on every Puppet pass.

```puppet
$our_db_name = 'aa '
ora_init_param { 'spfile/log_archive_dest_1':
  ensure => present,
  value  => "LOCATION=+ARCLOG/${our_db_name}"
}
```

Can you check if this is the case?

**Comment by cliles** [comment]
This is not the case, there is no trailing space in the var.

**Comment by hajee** [comment]
I have a couple of suggestions to look at:

- Can you try having evertything uppercase?:

```puppet
$our_db_name = 'aa '
ora_init_param { 'SPFILE/LOG_ARCHIVE_DEST_1':
  ensure => present,
  value  => "LOCATION=+ARCLOG/${our_db_name}"
}
```

- Can you check what resources the type sees: This is the query the type uses to see what SPFILE resources are available:

```sql
select 'SPFILE' as scope, t.isspecified, t.name, t.value, t.display_value, t.sid as for_sid from gv$spparameter t, gv$instance b where t.inst_id = b.instance_number and t.isspecified = 'TRUE'
```

**Comment by hajee** [comment]
If that is the case, then what happens if you do this:

```puppet
ora_init_param { 'SPFILE/LOG_ARCHIVE_DEST_1':
  ensure => present,
  value  => "LOCATION=+ARCLOG/${our_db_name} "
}
```

Watch the extra space after the variable!

**Comment by cliles** [comment]
It is still set on every run, this time the value is set with the trailing space.

```
Executing sql-command alter system set LOG_ARCHIVE_DEST_1='LOCATION=+ARCLOG=testdb ' scope=SPFILE sid='*'
```

I attempted to find a plsql trim() function to trim the t.name and t.value fields, but since I am a poor dba I was unsuccessful. Perhaps trim() (or equivalent) in the ruby code could work?

**Comment by hajee** [comment]
I could do a ruby trim, but since this code is for all parameters, this would also trim parameters with a required space at the end. I don't know if there are such parameters, but theoretically  it could.

**Comment by cliles** [comment]
I think that it would be better to use ||','|| so that sqlplus would to the pseudo-trim on such a parameter.

**Comment by hajee** [comment]
@cliles Is this still an issue?

**Comment by hajee** [comment]
No information. So I'm closing this issue
