### ISSUE TITLE
Defualt "grid" user cannot be overridden. 

### ISSUE THREAD

**Issue by megazza** [hajee/oracle#37]

**Comment by megazza** [comment]
For our installation our standard is oragrid.  Can we please have a variable substitution available for os_user - specifically in the asm_diskgroup creation .rb, but anywhere else also.

Thanks

**Comment by hajee** [comment]
Unfortunately the way it is implemented now, we need the `os_user` before it is read from the puppet type. A clean solution would be to have a `ora_db_defaults` and a `ora_asm_defaults` type. I have been experimenting with these, but they are not ready yet.

There is an other solution. It is a but crude, but it works. If we define a fact containing the `grid_user` I can use that one. 

I will try and make this one work.

**Comment by hajee** [comment]
Can you check this c9732537b5b5d810a78e69a3083192b65a35df0a

**Comment by megazza** [comment]
The /etc/puppetlabs/puppet/modules/oracle/lib/puppet/type/ora_asm_diskgroup.rb is using the oracle_access - it should be asm_access I believe?  

/etc/puppetlabs/puppet/modules/oracle/lib/puppet/type
[root@shou18l380g809 type]# cat ora_asm_diskgroup.rb
require 'pathname'
$:.unshift(Pathname.new(__FILE__).dirname.parent.parent)
$:.unshift(Pathname.new(__FILE__).dirname.parent.parent.parent.parent + 'easy_type' + 'lib')
require 'easy_type'
require 'ora_utils/oracle_access'
require 'ora_utils/title_parser'
require 'ora_utils/ora_tab'

module Puppet
  #
  # Create a new type oracle_user. Oracle user, works in conjunction
  # with the SqlResource provider
  #
  newtype(:ora_asm_diskgroup) do
    include EasyType
    include ::OraUtils::OracleAccess
    extend ::OraUtils::TitleParser

**Comment by megazza** [comment]
I just tried your new 1.2.0 version.   As per previosu verison I had to hack the grid to oragrid for now in ora_asm_diskgroup.rb.  However I now get this error with this version...

Jan  9 03:24:03 shou18l380g823 puppet-agent[20836]: Could not prefetch ora_asm_diskgroup provider 'simple': option username invalid for sql
Jan  9 03:24:03 shou18l380g823 puppet-agent[20836]: Could not set 'present' on ensure: option username invalid for sql at 190:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp
Jan  9 03:24:03 shou18l380g823 puppet-agent[20836]: Could not set 'present' on ensure: option username invalid for sql at 190:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp
Jan  9 03:24:03 shou18l380g823 puppet-agent[20836]: Wrapped exception:
Jan  9 03:24:03 shou18l380g823 puppet-agent[20836]: option username invalid for sql
Jan  9 03:24:03 shou18l380g823 puppet-agent[20836]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Ora_asm_diskgroup[RECO@+ASM]/ensure) change from absent to present failed: Could not set 'present' on ensure: option username invalid for sql at 190:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp


Can you advise of any other changes I need to make?

**Comment by hajee** [comment]
This is caused by stronger checks on the options given to a sql call. It is a bug. I will fix that right away.

**Comment by hajee** [comment]
Can you check this version?

**Comment by megazza** [comment]
Still getting this...

Jan  9 07:30:21 shou18l380g823 puppet-agent[17808]: Could not prefetch ora_asm_diskgroup provider 'simple': option username invalid for sql
Jan  9 07:30:21 shou18l380g823 puppet-agent[17808]: Could not set 'present' on ensure: uninitialized constant Puppet::OS_USER_NAME at 191:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp
Jan  9 07:30:21 shou18l380g823 puppet-agent[17808]: Could not set 'present' on ensure: uninitialized constant Puppet::OS_USER_NAME at 191:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp
Jan  9 07:30:21 shou18l380g823 puppet-agent[17808]: Wrapped exception:
Jan  9 07:30:21 shou18l380g823 puppet-agent[17808]: uninitialized constant Puppet::OS_USER_NAME
Jan  9 07:30:21 shou18l380g823 puppet-agent[17808]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Ora_asm_diskgroup[RECO@+ASM]/ensure) change from absent to present failed: Could not set 'present' on ensure: uninitialized constant Puppet::OS_USER_NAME at 191:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp


I have this in my init.pp...

    $default_asm_user = "oragrid"
    ora_asm_diskgroup{ 'RECO@+ASM':
      ensure          => 'present',
      au_size         => '1',
      compat_asm      => '11.2.0.0.0',
      compat_rdbms    => '10.1.0.0.0',
      diskgroup_state => 'MOUNTED',
      disks           => {'RECO_0000' => {'diskname' => 'RECO_0000', 'path' => '/dev/mapper/vg_data-lv_ora_asm4'},
                          'RECO_0001' => {'diskname' => 'RECO_0001', 'path' => '/dev/mapper/vg_data-lv_ora_asm5'},
                          'RECO_0002' => {'diskname' => 'RECO_0002', 'path' => '/dev/mapper/vg_data-lv_ora_asm6'}},
      redundancy_type => 'EXTERNAL',
      require         => Oradb::Opatch['19791420_db_patch'],
    }


I am using the latest ora_asm_diskgroup.rb  you provided.  Have I misinterpreted how to use this user variable?

**Comment by megazza** [comment]
I swtiched back to oracle_access ( above used asm_access by manual change) and I get s slightly different error now - which to me looks like I am definitely not declaring the asm user proverly (I am not an expert on puppet so please provide some guidance how I shoudl use it from my own init.pp)

If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
Jan  9 08:58:13 shou18l380g823 puppet-agent[44392]:    (at /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:816:in `set_default')
Jan  9 08:58:19 shou18l380g823 puppet-agent[44392]: createUser parameter on installdb 11.2.0.4_Linux-x86-64 can be removed, createUser feature is removed from this oradb module
Jan  9 08:58:19 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Oradb::Installdb[11.2.0.4_Linux-x86-64]/Notify[createUser parameter on installdb 11.2.0.4_Linux-x86-64 can be removed, createUser feature is removed from this oradb module]/message) defined 'message' as 'createUser parameter on installdb 11.2.0.4_Linux-x86-64 can be removed, createUser feature is removed from this oradb module'
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: Could not prefetch ora_asm_diskgroup provider 'simple': undefined local variable or method `default_asm_user' for Puppet::Type::Ora_asm_diskgroup:Class
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: Could not set 'present' on ensure: uninitialized constant Puppet::OS_USER_NAME at 192:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: Could not set 'present' on ensure: uninitialized constant Puppet::OS_USER_NAME at 192:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: Wrapped exception:
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: uninitialized constant Puppet::OS_USER_NAME
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Ora_asm_diskgroup[RECO@+ASM]/ensure) change from absent to present failed: Could not set 'present' on ensure: uninitialized constant Puppet::OS_USER_NAME at 192:/etc/puppetlabs/puppet/modules/jpmc_sa_asm_prov_11204/manifests/init.pp
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Oradb::Database[testDb_Create]/File[/local/stage/database_testDb_Create.rsp]) Dependency Ora_asm_diskgroup[RECO@+ASM] has failures: true
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Oradb::Database[testDb_Create]/File[/local/stage/database_testDb_Create.rsp]) Skipping because of failed dependencies
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Oradb::Database[testDb_Create]/File[/local/stage/jpmc_sa_asm_dbtemplate_testDb_Create.dbt]) Dependency Ora_asm_diskgroup[RECO@+ASM] has failures: true
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Oradb::Database[testDb_Create]/File[/local/stage/jpmc_sa_asm_dbtemplate_testDb_Create.dbt]) Skipping because of failed dependencies
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Oradb::Database[testDb_Create]/Exec[oracle database testDb_Create]) Dependency Ora_asm_diskgroup[RECO@+ASM] has failures: true
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: (/Stage[main]/Jpmc_sa_asm_prov_11204/Oradb::Database[testDb_Create]/Exec[oracle database testDb_Create]) Skipping because of failed dependencies
Jan  9 08:58:31 shou18l380g823 puppet-agent[44392]: Finished catalog run in 18.39 seconds

**Comment by megazza** [comment]
I have tried a few things now (correct my attempt above as its not a variable, its a def - sorry :() ...

    #$OS_USER_NAME = "oragrid"
    #require 'facter'
    #Facter.add(:OS_USER_NAME) do
#       setcode 'oragrid'
    #end
    #export FACTER_OS_USER_NAME='oragrid'; facter
    ora_asm_diskgroup{ 'RECO@+ASM':
     # environment => ["OS_USER_NAME=oragrid"], # this does not work
      default_asm_user => 'oragrid',
      ensure          => 'present',


It does not appear to take,   Like I say I am a newbie, so any guidance - thanks

**Comment by biemond** [comment]
Hi 

the best way to set a fact is following this doc https://docs.puppetlabs.com/facter/2.2/custom_facts.html#external-facts

make the following folder on every client puppet node
/etc/facter/facts.d/ # Puppet Open Source
/etc/puppetlabs/facter/facts.d/ # Puppet Enterprise

the easy way is to have a txt file in this facts.d folder.

.yaml: YAML data, in the following format:
        ---
        key1: val1
        key2: val2
        key3: val3

.json: JSON data, in the following format:
        {
            "key1": "val1",
            "key2": "val2",
            "key3": "val3"
        }

.txt: Key value pairs, in the following format:

  key1=value1
  key2=value2
  key3=value3

when you du sudo facter key1 you should see it.

**Comment by biemond** [comment]
Done by this pull request #39

**Comment by hajee** [comment]
thnx

**Comment by biemond** [comment]
should this line in sql.rb https://github.com/hajee/oracle/blob/master/lib/ora_utils/sql.rb#L71
not be like this  Facter.value(OS_USER_NAME) and not as Facter.value('OS_USER_NAME')

       def default_ora_user
         ENV[OS_USER_NAME] ||  Facter.value(OS_USER_NAME) || 'oracle'
      end
