### ISSUE TITLE
FORGE hajee/oracle install issue

### ISSUE THREAD

**Issue by megazza** [hajee/oracle#38]
Can you please look into why the install of the module fails, as I had to copy in the files (lib dir with all .rb files) manually following the junit failure (missing dir on symlink).

root@shou18l380g809 modules]# puppet module install /tmp/hajee-oracle-1.0.0.tar.gz --ignore-dependencies
Notice: Preparing to install into /etc/puppetlabs/puppet/modules ...
Notice: Installing -- do not interrupt ...
Error: No such file or directory - /etc/puppetlabs/puppet/modules/oracle/junit/latest
Error: Try 'puppet help module install' for usage

…you can see where it fails as the symlink dir does not actually exist…

[root@shou18l380g809 oracle]# pwd
/etc/puppetlabs/puppet/modules/oracle
[root@shou18l380g809 oracle]# ls -l ./*
-r--r--r-- 1 root pe-puppet   550 Dec 10 13:38 ./Gemfile
-r--r--r-- 1 root pe-puppet 10851 Oct 16 08:00 ./LICENSE
-r--r--r-- 1 root pe-puppet  1841 Dec 16 03:43 ./metadata.json
-r--r--r-- 1 root pe-puppet   103 Dec  9 13:14 ./Puppetfile
-r--r--r-- 1 root pe-puppet   178 Oct 16 08:00 ./Puppetfile.lock
-r--r--r-- 1 root pe-puppet   461 Dec 11 07:09 ./Vagrantfile

./files:
total 32
-r--r--r-- 1 root pe-puppet 366 Jan  7 03:15 diskgroup_create.sql.erb
-r--r--r-- 1 root pe-puppet 318 Oct 16 08:00 diskgroup_create.sql.erb.old
-r--r--r-- 1 root pe-puppet  56 Oct 16 08:00 diskgroup_destroy.sql.erb
-r--r--r-- 1 root pe-puppet 178 Oct 16 08:00 diskgroup_index.sql
-r--r--r-- 1 root pe-puppet  51 Oct 16 08:00 execute.sql.erb
-r--r--r-- 1 root pe-puppet 179 Oct 16 08:00 setup.sql.erb
-r--r--r-- 1 root pe-puppet 491 Oct 16 08:00 tablespace_index.sql
-r--r--r-- 1 root pe-puppet 194 Oct 16 08:00 update_schema_version.sql.erb

./junit:
total 20
drwxr-xr-x 2 root pe-puppet 4096 Dec 10 14:14 2014-12-10_21_14_37
drwxr-xr-x 2 root pe-puppet 4096 Dec 11 01:47 2014-12-11_08_47_01
drwxr-xr-x 2 root pe-puppet 4096 Dec 11 03:35 2014-12-11_10_35_22
drwxr-xr-x 2 root pe-puppet 4096 Jan  6 10:18 2014-12-11_10_37_46
drwxr-xr-x 2 root pe-puppet 4096 Jan  6 10:18 2014-12-11_10_45_33
lrwxrwxrwx 1 root root        19 Jan  6 10:18 latest -> 2014-12-11_10_48_14
[root@shou18l380g809 oracle]#

**Comment by hajee** [comment]
yesterday I've pushed a new version V1.1.0 to the forge that should remediate this problem. Can you please try that one?

**Comment by megazza** [comment]
Fixed - thanks.
