### ISSUE TITLE
asm_facts fail on windows

### ISSUE THREAD

**Issue by logicminds** [hajee/oracle#43]
The asm_facts fact is failing to load on my windows system which causes catalog compilation to fail.  I don't think these facts/providers/types were meant to be run on windows. 

https://github.com/hajee/oracle/blob/master/lib/facter/asm_facts.rb

```shell
Error: Could not retrieve local facts: file C:/ProgramData/PuppetLabs/puppet/var
/lib/puppet/type/ora_asm_diskgroup/name.rb not found
Error: Failed to apply catalog: Could not retrieve local facts: file C:/ProgramD
ata/PuppetLabs/puppet/var/lib/puppet/type/ora_asm_diskgroup/name.rb not found

```

**Comment by hajee** [comment]
Out of curiosity. Do you use the oracle module on Windows? I'm pretty sure it doesn't work. If so is there is specific reason, you install the module on windows?

**Comment by logicminds** [comment]
We are not using it on windows.  Because its used on our linux systems we have the module on our puppet master.  So by default puppet will use pluginsync to copy ALL facts, types and providers (even if you don't use them) during the agent run.  Its a annoying feature, but this is how it works.  So when your fact is loaded it errors out.

**Comment by hajee** [comment]
Ahh. Of course. I will look into it.

**Comment by logicminds** [comment]
The code to fix is in the PR.

**Comment by hajee** [comment]
Merged. Thanks for the PR.
