### ISSUE TITLE
ora_database register_database timeout

### ISSUE THREAD

**Issue by cliles** [hajee/oracle#57]
I've got an issue with creating a database via ora_database resource. The exec for register_database fails and returns 1. Running puppet in debug with trace doesn't return anything for stdout/stderr from the exec, but it looks like the ruby stacktrace is showing the command timeout.

Example failure is at http://fpaste.org/193650/

Is this command running as root? Shouldn't it run as the oracle user?

Running the exec from oracle user shell returns successful in < 1s

**Comment by hajee** [comment]
In version 1.5.4 we've changed the way we execute commands. Mainly to stabilise the ora_database.  What version are you using?

**Comment by cliles** [comment]
1.5.4

I ask if it's running as root since the env vars are not setup for root user. oraenv will wait for input, which could explain the timeout.
