### ISSUE TITLE
Error: undefined method `chop' for nil:NilClass

### ISSUE THREAD

**Issue by carroarmato0** [hajee/oracle#60]
Hi,

I'm trying to use the following to define a disk in ASM (doesn't look like its usage is documented, so I tried figuring out by looking at the rb code for the parameters) :

<pre>
ora_asm_volume {'disk':
  volume_device => '/dev/sdb',
  volume_name  => 'DISK1',
  diskgroup         => 'DATA',
}
</pre>

This returns the following:

<pre>
==> oracle12asm: Notice: Compiled catalog for oracle12asm.vagrantup.com in environment production in 1.32 seconds
==> oracle12asm: Error: undefined method `chop' for nil:NilClass
</pre>

Using    ruby 1.8.7 (2011-12-28 patchlevel 357) [x86_64-linux]   with Puppet 3.7.2 (Puppet Enterprise 3.7.0)

**Comment by hajee** [comment]
Can you specify a `-l` on the puppet command line. This will show the stack trace

**Comment by carroarmato0** [comment]
Ah apparently the ruby binary in my console is another version than the one puppet is using it seems:

<pre>
==> oracle12asm: Notice: Compiled catalog for oracle12asm.vagrantup.com in environment production in 1.67 seconds
==> oracle12asm: Error: undefined method `chop' for nil:NilClass
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:583:in `call'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:583:in `block (2 levels) in parse_title'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:572:in `each'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:572:in `block in parse_title'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:570:in `each'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:570:in `parse_title'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:301:in `to_hash'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:432:in `copy_as_resource'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:508:in `block in to_catalog'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:504:in `each'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:504:in `to_catalog'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:419:in `filter'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/catalog/compiler.rb:63:in `filter'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/indirection.rb:212:in `block in find'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/profiler/around_profiler.rb:58:in `profile'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/profiler.rb:51:in `profile'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/indirection.rb:211:in `find'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/apply.rb:217:in `block in main'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/context.rb:64:in `override'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet.rb:244:in `override'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/apply.rb:193:in `main'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/apply.rb:154:in `run_command'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block (2 levels) in run'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:507:in `plugin_hook'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block in run'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:488:in `exit_on_fail'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `run'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:146:in `run'
==> oracle12asm: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:92:in `execute'
==> oracle12asm: /opt/puppet/bin/puppet:8:in `<main>'

</pre>

**Comment by hajee** [comment]
What versions of:
- os
- puppet
- ruby
- oracle
- easy_type

are you using?

**Comment by carroarmato0** [comment]
OS:  SUSE Linux Enterprise Server 11 (x86_64) SP3  (*sigh*)
Puppet:  3.7.2 (Puppet Enterprise 3.7.0)
Ruby:  1.9.1
Oracle:  commit fc56cc053c1eaeabe7e76498dbb3f2a310ad4a9d  (currently latest checkout)
easy_type: commit f004ac0d07ce4dfa8f0cec99c4388a8909823445 (currently latest checkout)

**Comment by hajee** [comment]
You are right, it isn't well documented. We are still working on this. The syntax is:

```puppet
  ora_asm_volume{"${disk_group_name}:${volume_name}@+ASM1":
    size            => $size,
    volume_device   => $mount_point,
  }
```

So in your case this will likely be:
```puppet
ora_asm_volume {'DATA/DISK1@+ASM1':
  volume_device => '/dev/sdb',
  size              => '10G',
}
```

**Comment by carroarmato0** [comment]
Getting the following now,  still the chop issue though, I suspect this might be related to the ruby version I'm using.

I've dug deeper and using facter found the correct version:

<pre>
oracle12asm:~ # facter | grep ruby
rubyplatform => x86_64-linux
rubysitedir => /opt/puppet/lib/ruby/site_ruby/1.9.1
rubyversion => 1.9.3
</pre>

<pre>
==> oracle12asm: Notice: Compiled catalog for oracle12asm.vagrantup.com in environment production in 1.40 seconds
==> oracle12asm: Warning: Using 'sid/name' in title is deprecated. Use 'name@sid'.
==> oracle12asm:    (at /tmp/vagrant-puppet/modules-d458df27d499838cbfb80e125414b37b/oracle/lib/ora_utils/title_parser.rb:38:in `block in parse_asm_name')
==> oracle12asm: Error: undefined method `chop' for nil:NilClass
</pre>

To avoid the warning regarding the deprecated syntax I used the following:

<pre>
  ora_asm_volume {'DISK1@+ASM1':
    diskgroup     => 'DATA',
    volume_device => '/dev/sdb',
    size          => '10G',
  }
</pre>

**Comment by hajee** [comment]
Why do you think the ruby version is the cause? 

Can you try `puppet --debug`. This will show more of what is happening.

**Comment by hajee** [comment]
I made a mistake at the syntax. It should be:

```
ora_asm_volume {'DATA:DISK1@+ASM1':
  volume_device => '/dev/sdb',
  size              => '10G',
}
```

**Comment by carroarmato0** [comment]
Aha, the syntax indeed seems to have been the issue, perhaps that's why the chop function was failing.

Looks like it's "working" now, at least with regards to the subject of this issue which was due to incomplete documentation :)

Thanks for your help

**Comment by hajee** [comment]
We should improve on our error messages for this kind of problems.
