### ISSUE TITLE
Documentation: ora_exec description is wrong

### ISSUE THREAD

**Issue by awegmann** [hajee/oracle#62]
Hi Bert.

I tried to use `ora_exec` with a SQL-File. I think the documentation is wrong and incomplete.

I managed it to use it in this form:
```
 ora_exec { "@/tmp/setup_nls.sql":
    logoutput => on_failure,
    unless    => "select * from sys.PROPS$ where name='NLS_CHARACTERSET' and value$ = 'WE8ISO8859P15'"
  }
```

The important topic was, to put the '@' sign as first character in the name (or maybe the `statement` property). In contrast to the documentation, it seems not to be possible to put the SID inside the statement or at the end as you can do if you use `ora_exec` without file and write the statement down
directly as name or property.

Is my assumption correct? Further after looking at the code in `ora_exec.rb` there are a lot more properties possible than documented:

```

    map_title_to_sid(:statement) { /^((@?.*?)?(\@.*?)?)$/}

    parameter :name
    property  :statement
    parameter :sid

    parameter :timeout
    parameter :logoutput
    parameter :password
    parameter :username
    parameter :unless
```

Hm. When i try to understand the regex in `map_title_to_sid` it look like it's possible to use the format `@<filename>@<SID>` for the filename feature?
 
Nevertheless, the documentation is not complete for this feature. I can try to improve the documentation on `ora_exec` if you want and make a pull request. But I can't promise I will catch each topic right and complete. Pleas let me know if I should try to complete the documentation or if you will do this on your own.

Regards 
 Andreas

**Comment by hajee** [comment]
Andeas,

Thanks for pointing that out. Yes it seems the documentation in the README is not consistent. This is what it should be:

```
ora_exec{'@/tmp/some_file.sql@sid':}
```

When you want to execute a SQL file. When you want to execute a stement:

```
ora_exec{'select * from table where something=1@sid':}
```

I will change the doc's later this week.
