### ISSUE TITLE
ORA-00933 when changing tablespace datafile size and autoextend

### ISSUE THREAD

**Issue by stubennett** [hajee/oracle#66]
Changing the values for a tablespace datafile size and setting autoextend to on in the same puppet run causes an ORA-00933 error:

Notice: /Stage[main]/Profile::Oradb::Ora_tablespace/Ora_tablespace[XXX@XXX]/size: size changed '157286400' to '178257920'
Notice: /Stage[main]/Profile::Oradb::Ora_tablespace/Ora_tablespace[XXX@XXX]/autoextend: autoextend changed 'off' to 'on'
Notice: /Stage[main]/Profile::Oradb::Ora_tablespace/Ora_tablespace[XXX@XXX]/next: next changed '0' to '10485760'
Notice: /Stage[main]/Profile::Oradb::Ora_tablespace/Ora_tablespace[XXX@XXX]/max_size: max_size changed '0' to '1073741824'
Error: /Stage[main]/Profile::Oradb::Ora_tablespace/Ora_tablespace[XXX@XXX]: Could not evaluate: Error in execution of SQL command: alter database datafile '/oradata/XXX/test_tbs2.dbf'  resize 178257920  autoextend on  next 10485760  maxsize 1073741824 .
Found error ORA-00933: SQL command not properly ended

Oracle seems to want the resize and autoextend clauses in separate alter tablespace commands.

**Comment by hajee** [comment]
Thanks for logging this issue. To help resolving it, can you the part of the manifest creating this error? Also it helps if you specify what versions of Oracle and easy_type are you using?

**Comment by stubennett** [comment]
Thanks Hajee.  The part of the manifest is ora_tablespace.  I'm using Oracle 11.2.0.4 and easy_type version 0.13.0.

**Comment by hajee** [comment]
I would like to see the 
```
ora_tablespace {'XXX@XXX':
  ...
  size          => x,
  max_size  => y, 
  ..
}
```

**Comment by stubennett** [comment]
Here is the hieradata:
  'XXX@XXX':
    ensure:                     'present'
    datafile:                   '/oradata/XXX/test_tbs2.dbf'
    #contents:                   permanent
    bigfile:                    'no'
    size:                       170M
    logging:                    'yes'
    autoextend:                 'on'
    next:                       10M
    max_size:                   1G
    extent_management:          local
    segment_space_management:   auto

**Comment by hajee** [comment]
Although not the original issue, I see you are using `smallfile`  tablespaces. (e.g. `bigfile: no`). This implies that Oracle cannot change the size of the tablespace. So your original use case where you change the size of the dataafile, will **always** fail because Oracle prevents this.

**Comment by stubennett** [comment]
We are not using bigfiles so we were able to change the size using which seems to work ok:

    on_modify do | command_builder |
      command_builder.add("alter database #{dbfile_type} \'#{datafile}\' ", :sid => sid)
    end

and
    def dbfile_type
      (self['contents'] == :temporary) ? 'tempfile' : 'datafile'
    end

**Comment by hajee** [comment]
Your yaml create's the following puppet statement:
```puppet
ora_tablespace{'XXX':
  ensure             => 'present',
  datafile           => '/dbs/test_tbs2.dbf',
  contents          => permanent,
  bigfile            => 'no',
  size               => 5M,
  logging            => 'yes',
  autoextend         => 'on',
  next               => 10M,
  max_size           => 1G,
  extent_management  => local,
  segment_space_management  => auto,
}
```
Create's an invalid statement. If your don't specify the `contents` attribute it create's the tablespace correctly. This is a bug and is fixed in commit 1b734ad506d506dd27e5ffebc025e7ce1dbdedd4

If you change the size, As expected I get the error:
```
ORA-32773: operation not supported for smallfile tablespace XXX
```
This is expected behaviour ad the way to fix this, is using bigfile tablespaces.

The changes other changes in the manifest als seem to create a wrong statement. I will look into this later

**Comment by stubennett** [comment]
Thanks for looking at this.  We are creating the tablespaces manually and we can resize these using the entries above.  The only issue is if we try and change the size of an existing tablespace as well as setting autoextend on.

**Comment by hajee** [comment]
commit cfc14e93248565ab896dbd81d0b2bf3992aa6b54 should fix your problems when changing the properties:

- `next`
- `max_size`
- `autoextend`

Like I said before, it will still error on the size attribute unless you use a `bigfile` tablespace.

Can you check this commit?

**Comment by stubennett** [comment]
Great.  Thats fixed it.  Thanks.
